### ISSUE TITLE
Updating rabbitmq to 3.11.0

### ISSUE THREAD

**Issue by ianwalter** [render-examples/rabbitmq#2]
Not sure how to do this because if I update the base image, I get this failure on deploy:
```
Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only
```

**Comment by kylezinter** [comment]
I've also been struggling with this, as well as trying to get a cluster set up on Render.

I was able to successfully deploy 3.11 with the below render.yml, notice the change on the disk `mountPath`. This 'mnesia' workaround was discussed in quite a few threads I found on this issue but it don't believe this is an ideal or recommended solution. I'm also not clear on what the downsides are yet though. I expected it to be that data would not persist across restarts any longer but I'm not seeing that happen, users and other data appear to persist.

```
  - type: web
    name: rabbitmq
    env: docker
    rootDir: my/root/dir
    envVars:
      - key: RABBITMQ_ERLANG_COOKIE
        generateValue: true
      - key: RABBITMQ_DEFAULT_USER
        value: rabbitmq
      - key: RABBITMQ_DEFAULT_PASS
        generateValue: true
    disk:
      name: rabbitmq-disk
      mountPath: /var/lib/rabbitmq/mnesia
      sizeGB: 10
```

Have not had success with a cluster formation.
